# Generated by Django 4.2.2 on 2023-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
